name: localizator
description: generate dart locale files from json.
version: 0.3.0
homepage: https://gitlab.com/NyAkovlev/localizator

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_style: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter